[package]
name = "guitar"
version = "0.1.0"
description = "Terminal based git interface"
authors = ["rattleworks <gasimov.abdulali@gmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.29.0"
git2 = "0.20.2"
colored = "3"
chrono = "0.4"
rand = "0.9"
edtui = "0.9.8"
encoding_rs = "0.8.35"
im = "15.1.0"
indexmap = "2.12.1"
